import Head from "next/head";
import Banner from "../src/components/home/banner";
import Row from "../src/components/home/row";
import requests from "./api/requests";
import Layout from "../src/components/layout/layout";
import { dehydrate, QueryClient, useQuery } from "react-query";
import { fetchMovies } from "../src/hooks/useFetchMovie";

export default function Home() {
  return (
    <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Banner />
        <Row
          title="NEFLIX ORIGINAL"
          id="NO"
          fetchUrl={requests.fetchNetflixOriginals}
          isLarge={true}
        />
        <Row
          title="Top Rated"
          id="TR"
          fetchUrl={requests.fetchTopRated}
          isLarge={false}
        />
        <Row
          title="Trending Now"
          id="TN"
          fetchUrl={requests.fetchTrending}
          isLarge={false}
        />
        <Row
          title="Action Movies"
          id="AN"
          fetchUrl={requests.fetchActionMovies}
          isLarge={false}
        />
        <Row
          title="Comedy Movies"
          id="CM"
          fetchUrl={requests.fetchComedyMovies}
          isLarge={false}
        />
      </Layout>
    </>
  );
}
