import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Nav from "../components/nav";
import Banner from "../components/banner";
import Row from "../components/row";
import requests from "./api/requests";
import Footer from "../components/footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Banner />
      <Row
        title="NEFLIX ORIGINAL"
        id="NO"
        fetchUrl={requests.fetchNetflixOriginals}
        isLarge={true}
      />
      <Row title="Top Rated" id="TR" fetchUrl={requests.fetchTopRated} />
      <Row title="Trending Now" id="TN" fetchUrl={requests.fetchTrending} />
      <Row
        title="Action Movies"
        id="AN"
        fetchUrl={requests.fetchActionMovies}
      />
      <Row
        title="Comedy Movies"
        id="CM"
        fetchUrl={requests.fetchComedyMovies}
      />
      <Footer />
    </>
  );
}
